openapi: 3.0.3
info:
  title: Form Provider
  description: This document describes REST API of 'Form provider scripts'
  version: '1.0'
servers:
  - url: http://localhost:7070
    description: Generated server url
paths:
  /form-scripts:
    get:
      summary: Get all form scripts
      operationId: getFormScriptList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScriptListResponseBody'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json: { }
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
  /form-scripts/{formScriptName}:
    post:
      summary: Add form script
      operationId: createFormScript
      parameters:
        - name: formScriptName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScriptRequestBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '401':
          description: Unauthorized
          content:
            application/json: { }
        '403':
          description: Forbidden
          content:
            application/json: { }
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
    put:
      summary: Update form script
      operationId: updateFormScript
      parameters:
        - name: formScriptName
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScriptRequestBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json: {}
        '401':
          description: Unauthorized
          content:
            application/json: {}
        '403':
          description: Forbidden
          content:
            application/json: {}
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
components:
  schemas:
    ScriptListResponseBody:
      type: object
      properties:
        scripts:
          type: string
    ScriptRequestBody:
      type: object
      properties:
        content:
          type: string
    DetailedErrorResponse:
      type: object
      properties:
        traceId:
          type: string
        type:
          type: string
        message:
          type: string
        localizedMessage:
          type: string
