openapi: 3.0.3
info:
  title: Registry regulations admin-portal
  description: This document describes REST API of 'Get Form Scripts'
  version: '1.0'
servers:
  - url: http://localhost:7070
    description: Generated server url
paths:
  /versions/candidates/{versionCandidateId}/form-scripts/:
    get:
      summary: Get Form Scripts
      operationId: getFormScripts
      parameters:
        - name: versionCandidateId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormScriptsResponse'
        '401':
          description: Unauthorized
          content:
            application/json: { }
        '403':
          description: Forbidden
          content:
            application/json: { }
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
components:
  schemas:
    FormScriptsResponse:
      type: object
      properties:
        scripts:
          type: string
    DetailedErrorResponse:
      type: object
      properties:
        traceId:
          type: string
        type:
          type: string
        message:
          type: string
        localizedMessage:
          type: string
